### ISSUE TITLE
Contradictions about PR's

### ISSUE THREAD

**Issue by fodfodfod** [roboblazers7617/code-standards#6] opened 2024-11-06 21:09 UTC
https://github.com/roboblazers7617/code-standards/blob/afdcb93106a8ea6e44617e9e5afd68a19ccd4e3c/docs/git-workflow.md?plain=1#L39

This says that PR's should be small, incremental changes and large, major changes.

**Comment by ApolloFops** [comment] 2024-11-06 21:11
Duplicate of #3.

**Closed as completed by ApolloFops** 2024-11-06 21:10 UTC
